### ISSUE TITLE
Lack of Vertical Switches

### ISSUE THREAD

**Issue by ColonelGerdauf** [ai03-2725/MX_Alps_Hybrid#20]
This is especially problematic for situations where we want to make a numpad, as it uses a pair of vertical 2U switches.

**Comment by perigoso** [comment]
I suggest my library, should have what you are looking for https://github.com/perigoso/Switch_Keyboard

**Comment by ai03-2725** [comment]
Apologize for the ridiculous delay; finally got around to checking pending PRs after too long.  
#10 should solve this issue; if not please comment further and I'll see if I can add the missing footprints.
