### ISSUE TITLE
This library is not being maintained.

### ISSUE THREAD

**Issue by perigoso** [ai03-2725/MX_Alps_Hybrid#21]
If anyone is looking for an actively maintained library I will point you to [this one](https://github.com/perigoso/Switch_Keyboard), which started as a fork of this one, where work was being done in order to get it upstreamed into the KiCad official libraries.

**Comment by ai03-2725** [comment]
I apologize for the lack of maintenance; I was very busy with life amidst difficult situations and did not have time to check on the repository. 
I am back and alive now, so this issue will be closed.
